import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE.
Edit the TypeScript source in src/ instead of editing main.js directly.
*/`;

const production = process.argv[2] === 'production';
const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtinModules,
  ],
  format: 'cjs',
  target: 'es2021',
  logLevel: 'info',
  sourcemap: production ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minifyIdentifiers: production,
  minifyWhitespace: production,
  // Keep escape sequences as escapes. Syntax minification can rewrite strings
  // containing Markdown hard-break spaces into multiline template literals,
  // which makes the generated release artifact fail git whitespace checks.
  minifySyntax: false,
});

if (production) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
